language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"

before_script:
  - sudo apt-get install pychecker rpm python-rpm
install:
  - pip install pybuilder

script: "pyb install_dependencies analyze run_integration_tests --debug"

notifications:
  email:
    - arne.hilmann@immobilienscout24.de
    - michael.gruber@immobilienscout24.de
