before_script: "sudo apt-get install python-coverage python-django pychecker pymetrics python-setuptools python-mock && sudo easy_install http://python-builder.googlecode.com/files/python-builder-0.6.2.tar.gz"
script: "pyb"
notifications:
  email:
    - aelgru@gmail.com

