language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
before_script: sudo apt-get install pychecker rpm python-rpm
install:
  - pip install pybuilder
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: "pyb --debug"
notifications:
  email:
    - michael.gruber@immobilienscout24.de
    - arne.hilmann@immobilienscout24.de
