language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"

before_script:
  - sudo apt-get install pychecker rpm python-rpm

install:
  - pip install pybuilder
  - pyb install_dependencies

script: "pyb analyze run_integration_tests --debug"
